version: "3.7"

services:
  web:
    image: ghcr.io/cryptosharks131/lndg:v1.0.2@sha256:14920a101bcb992fbdb089b9ff9527229d97729a56a577d47f7f4ac8404a7bd6
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "8889:8000"
    volumes:
      - ${LND_DATA_DIR}:/root/.lnd:ro
      - ${APP_DATA_DIR}/data:/lndg/data:rw
    command:
      - sh
      - -c
      - python initialize.py -net '$BITCOIN_NETWORK' -server '$LND_IP:$LND_GRPC_PORT' -pw '$APP_PASSWORD' -d && supervisord && python manage.py runserver 0.0.0.0:8000
    networks:
      default:
        ipv4_address: 10.21.21.89
