version: "3.7"

services:
  web:
    image: ghcr.io/cryptosharks131/lndg:latest@sha256:32e1d0385009563124bd88aa1b40a7fea1b492da31be1594e2e2ab3beb1ed99e
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "8889:8000"
    volumes:
      - ${LND_DATA_DIR}:/root/.lnd:ro
      - ${APP_DATA_DIR}/db.sqlite3:/lndg/db.sqlite3
    command:
      - sh
      - -c
      - python initialize.py -dx -net '$BITCOIN_NETWORK' -server '$LND_IP:$LND_GRPC_PORT' -d && python manage.py migrate && python manage.py collectstatic --no-input && supervisord && python manage.py runserver 0.0.0.0:8000
    networks:
      default:
        ipv4_address: 10.21.21.89
