version: "3.7"

services:
  web:
    image: ghcr.io/cryptosharks131/lndg:latest
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "8889:8000"
    volumes:
      - ${LND_DATA_DIR}:/lnd:ro
    command:
      - sh
      - -c
      - python initialize.py -dx -net 'mainnet' -server 'localhost:10009' -d && python manage.py migrate && python manage.py collectstatic --no-input && supervisord && python manage.py runserver 0.0.0.0:8000
    networks:
      default:
        ipv4_address: 10.21.21.89
