version: "3.7"

services:
  web:
    image: ghcr.io/cryptosharks131/lndg:v1.0.0@sha256:7260e3117b5b44691c6f61f0b54d58a49d8382e9ad7431da39232d6a18b013ec
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "8889:8000"
    volumes:
      - ${LND_DATA_DIR}:/root/.lnd:ro
      - ${APP_DATA_DIR}/db.sqlite3:/lndg/db.sqlite3
    command:
      - sh
      - -c
      - python initialize.py -net '$BITCOIN_NETWORK' -server '$LND_IP:$LND_GRPC_PORT' -pw '$APP_PASSWORD' -d && supervisord && python manage.py runserver 0.0.0.0:8000
    networks:
      default:
        ipv4_address: 10.21.21.89
