version: "3.7"

services:
  web:
    image: ghcr.io/cryptosharks131/lndg:latest@sha256:42bcceaa2732d96153445f791564552bc787226fcf9471dc2b6d6cde77c8d29e
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "8889:8000"
    volumes:
      - ${LND_DATA_DIR}:/root/.lnd:ro
      - ${APP_DATA_DIR}/data:/lndg/data:rw
    command:
      - sh
      - -c
      - python initialize.py -net '$BITCOIN_NETWORK' -server '$LND_IP:$LND_GRPC_PORT' -pw '$APP_PASSWORD' -d && supervisord && python manage.py runserver 0.0.0.0:8000
    networks:
      default:
        ipv4_address: 10.21.21.89
